---
- name: Install kopia
  ansible.builtin.import_tasks: install.yml
  tags:
    - kopia
    - kopia:install

- name: Configure GCS repository
  ansible.builtin.import_tasks: gcs.yml
  when: kopia_gcs_bucket is defined
  tags:
    - kopia
    - kopia:gcs
